config/routes.rb
Rails.application.routes.draw do
  get 'pages/about', as: 'about'

  root :to => 'flights#search'
  resources :reservations
  resources :users
  resources :flights
  resources :planes

  get '/login' => 'session#new', as: 'login'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

end

app/models/flight.rb
class Flight < ActiveRecord::Base
  belongs_to :plane
  has_many :reservations
  has_many :users, :through => :reservations
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  before_action :set_flight, only: [:show, :edit, :update, :destroy]

  def search

  end

  # GET /flights
  # GET /flights.json
  def index
    @flights = Flight.all
  end

  # GET /flights/1
  # GET /flights/1.json
  def show
  end

  # GET /flights/new
  def new
    @flight = Flight.new
  end

  # GET /flights/1/edit
  def edit
  end

  # POST /flights
  # POST /flights.json
  def create
    @flight = Flight.new(flight_params)

    respond_to do |format|
      if @flight.save
        format.html { redirect_to @flight, notice: 'Flight was successfully created.' }
        format.json { render :show, status: :created, location: @flight }
      else
        format.html { render :new }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flights/1
  # PATCH/PUT /flights/1.json
  def update
    respond_to do |format|
      if @flight.update(flight_params)
        format.html { redirect_to @flight, notice: 'Flight was successfully updated.' }
        format.json { render :show, status: :ok, location: @flight }
      else
        format.html { render :edit }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flights/1
  # DELETE /flights/1.json
  def destroy
    @flight.destroy
    respond_to do |format|
      format.html { redirect_to flights_url, notice: 'Flight was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flight
      @flight = Flight.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def flight_params
      params.require(:flight).permit(:date, :origin, :destination, :plane_id)
    end
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/flights/_form.html.erb
<%= form_for(@flight) do |f| %>
  <% if @flight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@flight.errors.count, "error") %> prohibited this flight from being saved:</h2>

      <ul>
      <% @flight.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="form-group">
    <%= f.label :origin %><br>
    <%= f.text_field :origin %>
  </div>
  <div class="form-group">
    <%= f.label :destination %><br>
    <%= f.text_field :destination %>
  </div>
  <div class="form-group">
    <%= f.label :plane_id %><br>
    <%= f.select :plane_id, Plane.pluck(:name, :id), :include_blank => true %>
  </div>
  <div class="actions">
    <%= f.submit :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/flights/bookings.html.erb
<h1>Bookings</h1>

app/views/flights/edit.html.erb
<h1>Editing Flight</h1>

<%= render 'form' %>

<%= link_to 'Show', @flight %> |
<%= link_to 'Back', flights_path %>

app/views/flights/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Flights</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Origin</th>
      <th>Destination</th>
      <th>Plane</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @flights.each do |flight| %>
      <tr>
        <td><%= flight.date %></td>
        <td><%= flight.origin %></td>
        <td><%= flight.destination %></td>
        <td><%= flight.plane_id %></td>
        <td><%= link_to 'Show', flight %></td>
        <td><%= link_to 'Edit', edit_flight_path(flight) %></td>
        <td><%= link_to 'Destroy', flight, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Flight', new_flight_path %>

app/views/flights/new.html.erb
<div class="addForm">
<h1>Add Flight</h1>

<%= render 'form' %>

<%= link_to 'Back', flights_path %>
</div>

app/views/flights/search.html.erb
<div class="headline">
  <h1><span>Burning</span><br>LCD AIRLINES.</h1>

  <div class="mouse">
      <span></span>
  </div>
</div>

<div id="searchWrapper">
<h1>Book flights</h1>

<div id="main">
  <div id="formView"></div>
  <div id="flightSearchView"></div>
</div>
<div id="flight-book">
  <div id="div-seats"></div>
  <div id="reserve-panel"></div>
</div>

</div>

<script id="formViewTemplate" type="text/template">
  <!-- <label>From</label> -->
    <input type="text" id="origin" placeholder="Departure airport (SYD)" autofocus/>
  <!-- <label>To</label> -->
    <input type="text" id="destination" placeholder="Arrival airport (JFK)"/>

  <button>Search</button>
</script>



<script id="flightInfo" type="text/template">
<h2>Choose Flight</h2>
  <table>
    <thead>
      <tr>
        <th>Date</th>
        <th>Flight</th>
        <th>From <i class="fa fa-angle-double-right"></i> To</th>
        <th>Plane</th>
      </tr>
    </thead>

    <tbody id="flightTableBody">

    </tbody>
  </table>

</script>

<script id="flightTableTemplate" type="text/template">
<tr>
  <td>{{ date }}</td>
  <td>{{ id }}</td>
  <td>{{ origin  }} <span><i class="fa fa-plane"></i> {{ destination }}</td>
  <td>{{ plane_name }}</td>
  <td><button>Choose</button></td>
</tr>
</script>

<script id="bookingFlightInfo" type="text/template">
<div class="user_page">
  <div class="flight flight-active">
    <div class="flight-cities">
      <div class="flight-city"> {{ origin  }}</div>
        <div class="flight-progress"><div class="flight-progress-track">&#9992;</div></div>
      <div class="flight-city">{{ destination }}</div>
    </div>


<div class="flight-leg flight-from">
  <table class="flight-details">
    <thead>
      <tr>
        <td></td>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>{{date}}</td>
      </tr>
    </tbody>
  </table>
</div>
</div>
  </div>
</div>
</script>


<script id="seatTemplate" type="text/template">
  <table id="seat-view">
    <tbody id="seat-body">

    </tbody>
  </table>

</script>

<script id="reserve-panel-template" type="text/template">
  <div id="seat_number"></div><br>
  <button id="reserve_seat">Make reservation</button>
</script>

<script type="text/javascript">

app.user = <%== @current_user.to_json %>   // uses ruby to get id of login user

</script>

<script type="text/template" id="ticketTemplate">
  <div class="ticket-container">
    <div class="box">
      <div class="ticket">
        <span class="airline">LCD Airlines</span>
        <span class="airline airlineslip">LCD Airlines</span>
        <span class="boarding">Boarding pass</span>
        <div class="ticket-content">
          <span class="originTicket">{{origin}}</span>
          <span class="plane"><?xml version="1.0" ?><svg clip-rule="evenodd" fill-rule="evenodd" height="60" width="60" image-rendering="optimizeQuality" shape-rendering="geometricPrecision" text-rendering="geometricPrecision" viewBox="0 0 500 500" xmlns="http://www.w3.org/2000/svg"><g stroke="#222"><line fill="none" stroke-linecap="round" stroke-width="30" x1="300" x2="55" y1="390" y2="390"/><path d="M98 325c-9 10 10 16 25 6l311-156c24-17 35-25 42-50 2-15-46-11-78-7-15 1-34 10-42 16l-56 35 1-1-169-31c-14-3-24-5-37-1-10 5-18 10-27 18l122 72c4 3 5 7 1 9l-44 27-75-15c-10-2-18-4-28 0-8 4-14 9-20 15l74 63z" fill="#222" stroke-linejoin="round" stroke-width="10"/></g></svg></span>
          <span class="destTicket">{{destination}}</span>

          <span class="originTicket originTicketslip">{{origin}}</span>
          <span class="plane planeslip"><?xml version="1.0" ?><svg clip-rule="evenodd" fill-rule="evenodd" height="50" width="50" image-rendering="optimizeQuality" shape-rendering="geometricPrecision" text-rendering="geometricPrecision" viewBox="0 0 500 500" xmlns="http://www.w3.org/2000/svg"><g stroke="#222"><line fill="none" stroke-linecap="round" stroke-width="30" x1="300" x2="55" y1="390" y2="390"/><path d="M98 325c-9 10 10 16 25 6l311-156c24-17 35-25 42-50 2-15-46-11-78-7-15 1-34 10-42 16l-56 35 1-1-169-31c-14-3-24-5-37-1-10 5-18 10-27 18l122 72c4 3 5 7 1 9l-44 27-75-15c-10-2-18-4-28 0-8 4-14 9-20 15l74 63z" fill="#222" stroke-linejoin="round" stroke-width="10"/></g></svg></span>
          <span class="destTicket destTicketslip">{{destination}}</span>
          <div class="sub-content">
            <span class="watermark">LCD LCD</span>
            <span class="name">PASSENGER NAME<br><span>{{app.user.name}}</span></span>
            <span class="flight">FLIGHT N&deg;<br><span>{{flight_id}}</span></span>
            <span class="gate">GATE<br><span>11B</span></span>
            <span class="seat">SEAT<br><span>{{seat_row}} {{seat_col}}</span></span>
            <span class="boardingtime">BOARDING TIME<br><span>{{date}}</span></span>

             <span class="flight flightslip">FLIGHT N&deg;<br><span> {{flight_id}}</span></span>
              <span class="seat seatslip">SEAT<br><span>{{seat_row}} {{seat_col}}</span></span>
             <span class="name nameslip">PASSENGER NAME<br><span>{{app.user.name}}</span></span>
          </div>
        </div>
        <div class="barcode"></div>
        <div class="barcode slip"></div>
      </div>
    </div>
  </div>
</script>

app/views/flights/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @flight.date %>
</p>

<p>
  <strong>Origin:</strong>
  <%= @flight.origin %>
</p>

<p>
  <strong>Destination:</strong>
  <%= @flight.destination %>
</p>

<p>
  <strong>Plane:</strong>
  <%= @flight.plane_id %>
</p>

<%= link_to 'Edit', edit_flight_path(@flight) %> |
<%= link_to 'Back', flights_path %>