config/routes.rb
Rails.application.routes.draw do
  get 'pages/about', as: 'about'

  root :to => 'flights#search'
  resources :reservations
  resources :users
  resources :flights
  resources :planes

  get '/login' => 'session#new', as: 'login'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LCDAirlines</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header class="main_h">
    <div class="row">

    <%= link_to "LCD.", root_path, :class => "logo" %>

    <div class="mobile-toggle">
      <span></span>
      <span></span>
      <span></span>
    </div>
<nav>
  <ul>
    <% if @current_user.present? %>
      <% if @current_user.admin? %>
      <li><%= link_to "Add Planes", new_plane_path, :class => '.sec01' %></li>
      <li><%= link_to "Add Flights", new_flight_path, :class => '.sec02' %></li>
      <!-- <li><%= link_to "All planes", planes_path %></li> -->
      <!--<li><%= link_to "All users", users_path %></li> -->

      <% end %>

      <li><%= link_to "Logout", login_path, :method => 'delete', :class => '.sec03' %></li>
      <!-- <span>Welcome <%= @current_user.name %>!</span> -->
      <li><%= link_to "Welcome #{@current_user.name}!", user_path(@current_user.id), :class => '.sec04' %></li>


      <% else %>
        <li><%= link_to "About", about_path, :class => ".sec03" %></li>

      <li><%= link_to "Sign up", new_user_path, :class => ".sec03" %></li>
      <li><%= link_to "Sign in", login_path, :class => ".sec04" %></li>
      <% end %>
      </ul>
</nav>

</div> <!--row-->
</header>

<%= yield %>


<footer><p>Copyright&copy; 2017</p></footer>
</body>
</html>